language: java
jdk: openjdk11
sudo: true
dist: xenial

# Make it possible to run tests on a local Chrome
before_install:
 - export CHROME_BIN=/usr/bin/google-chrome

addons:
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable


install: true
script: ./.travis.script.sh

# Cache requires a master build
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.m2
  - .driver
  - selenium_standalone_zips

before_cache:
  # remove all build artifacts
  - rm -rf $HOME/.m2/repository/com/vaadin/tutorial/crm