/**
 * This file has been autogenerated as it didn't exist or was made for an older
 * incompatible version.
 *
 * This file can be used for manual configuration. It will not be modified
 * if the flowDefaults constant exists.
 */
const merge = require('webpack-merge');
const flowDefaults = require('./webpack.generated.js');

// Begin workaround: needed until Flow 6.0.offline-SNAPSHOT gets this fix:
// https://github.com/vaadin/flow/pull/9550
const cssLoaders = flowDefaults.module.rules.find(r => r.test && r.test.toString() == '/\\.css$/i');
const containsLitCssLoader = cssLoaders.use.find(o => o.loader === 'lit-css-loader') !== undefined;
if (!containsLitCssLoader) {
  cssLoaders.use.unshift(
    {
      loader: "lit-css-loader"
    },
    {
      loader: "extract-loader"
    }
  );
}
// End workaround

/**
 * To change the webpack config, add a new configuration object in
 * the merge arguments below:
 */
module.exports = merge(flowDefaults,
  // Override default configuration
  // {
  //   mode: 'development',
  //   devtool: 'inline-source-map',
  // },

  // Add a custom plugin
  // (install the plugin with `npm install --save-dev webpack-bundle-analyzer`)
  // {
  //   plugins: [
  //     new require('webpack-bundle-analyzer').BundleAnalyzerPlugin({
  //       analyzerMode: 'static'
  //     })
  //   ]
  // },
);
