/**
 * This file has been autogenerated as it didn't exist or was made for an older incompatible version.
 * This file can be used for manual configuration will not be modified if the flowDefaults constant exists.
 */
const merge = require('webpack-merge');
const path = require('path');
const flowDefaults = require('./webpack.generated.js');

// TODO: use `lit-html-loader` by default
// replace the default `raw-loader` for .css files with the custom `lit-css-loader`
flowDefaults.module.rules.filter(rule => rule.test.test('.css')).forEach(rule => {
  rule.use = ['lit-css-loader'];
});

module.exports = merge(flowDefaults,
  // Add a custom plugin
  // {
  //   plugins: [
  //     // (install the plugin with `npm install --save-dev webpack-bundle-analyzer`)
  //     new (require('webpack-bundle-analyzer').BundleAnalyzerPlugin)({
  //       analyzerMode: 'static',
  //       reportFilename: '/Users/viktor/IdeaProjects/crm-tutorial-typescript/target/webpack-bundle-size-report.html'
  //     })
  //   ]
  // },

  // register a custom local webpack loader
  {
    resolveLoader: {
      alias: {
        'lit-css-loader': path.join(__dirname, 'lit-css-loader'),
      },
    }
  },
);

/**
 * This file can be used to configure the flow plugin defaults.
 * <code>
 *   // Add a custom plugin
 *   flowDefaults.plugins.push(new MyPlugin());
 *
 *   // Update the rules to also transpile `.mjs` files
 *   if (!flowDefaults.module.rules[0].test) {
 *     throw "Unexpected structure in generated webpack config";
 *   }
 *   flowDefaults.module.rules[0].test = /\.m?js$/
 *
 *   // Include a custom JS in the entry point in addition to generated-flow-imports.js
 *   if (typeof flowDefaults.entry.index != "string") {
 *     throw "Unexpected structure in generated webpack config";
 *   }
 *   flowDefaults.entry.index = [flowDefaults.entry.index, "myCustomFile.js"];
 * </code>
 * or add new configuration in the merge block.
 * <code>
 *   module.exports = merge(flowDefaults, {
 *     mode: 'development',
 *     devtool: 'inline-source-map'
 *   });
 * </code>
 */
